# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - dev
      - release*

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      docker ps -a
      docker --version
    displayName: "Check Docker installation "

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        make local_build

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'admin access to i-platform-dev AWS account(151924297945)'
      regionName: 'us-east-1'
      imageSource: 'imagename'
      sourceImageName: 'devops-tools'
      repositoryName: '151924297945.dkr.ecr.us-east-1.amazonaws.com'