# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - dev
      - release*
      - iss*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        make local_build

  - bash: |
      IMAGE_COMMIT="$(make get_commit)"
      echo "##vso[task.setvariable variable=image_commit]$IMAGE_COMMIT"

  - task: ECRPushImage@1
    inputs:
      awsCredentials: "admin access to i-platform-dev AWS account(151924297945)"
      regionName: "us-east-1"
      imageSource: "imagename"
      sourceImageName: "devops-tools"
      repositoryName: "devops-tools"
      pushTag: $(image_commit)
